# Generated by Django 5.0.2 on 2024-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contraseña', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraseñas',
            name='nombre',
            field=models.CharField(),
        ),
    ]
